export default {
  index: 'Overview',
  targets: 'Targets & Runs',
  specifications: 'Specifications',
  explore: 'Explore',
  'library-resources': 'Library & Resources',
  'apis-portals': 'APIs & Portals',
  performance: 'Performance',
  benchmarks: 'Benchmarks',
  agent: 'Agent',
  dashboard: 'Dashboard',
  'validate-against-contracts': 'Validate Against Contracts',
  analytics: 'Analytics',
  tokens: 'Tokens',
  notifications: 'Notifications',
  redaction: 'Redaction',
  'agent-access': 'Agent Access',
  quotas: 'Plans & Quotas',
}
