export default {
  index: 'Overview',
  'contract-http': 'Contract HTTP',
  'contract-flow': 'Contract Flow',
  'test-api': 'Test Shape',
  'http-client': 'HTTP Requests',
  assertions: 'Assertions',
  'env-and-secrets': 'Variables & Secrets',
  'data-driven': 'Data-Driven',
  'local-data': 'Local Data',
  'shared-state': 'Shared State',
  'test-control': 'Control Flow',
  observability: 'Logs, Traces, Metrics',
  configuration: 'Shared Config',
  plugins: 'Plugins',
  'auth-plugin': 'Auth Plugin',
  'graphql-plugin': 'GraphQL Plugin',
  'grpc-plugin': 'gRPC Plugin',
  'browser-plugin': 'Browser Plugin',
}
