export default {
  index: 'Overview',
  'test-api': 'Test API & Builder',
  'data-driven': 'Data-Driven Tests',
  'local-data': 'Local Test Data',
  configuration: 'Configuration',
  'http-client': 'HTTP Client',
  'env-and-secrets': 'Environment & Secrets',
  assertions: 'Assertions & Validation',
  'test-control': 'Test Lifecycle & Control',
  observability: 'Observability',
  plugins: 'Plugin System',
  'auth-plugin': 'Auth Plugin',
  'graphql-plugin': 'GraphQL Plugin',
  'browser-plugin': 'Browser Plugin',
}
